// AutolinkedNativeModules.g.cs contents generated by "npx @react-native-community/cli autolink-windows"

using System.Collections.Generic;

// Namespaces from react-native-star-io10
using StarMicronics.ReactNative.StarIO10;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        { 
            // IReactPackageProviders from react-native-star-io10
            packageProviders.Add(new StarMicronics.ReactNative.StarIO10.ReactPackageProvider());
        }
    }
}
